pageTitle: Vault Dashboard
showNavigation: false
showFooter: false
actions:
  - title: "Shutdown Vault"
    shell: ssh -i /ssh/id_rsa root@192.168.2.3 'poweroff'
    icon: "&#128452;"
    timeout: 10
  - title: "Restart Vault"
    shell: ssh -i /ssh/id_rsa root@192.168.2.3 'poweroff --reboot'
    icon: "&#128452;"
    timeout: 10