services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.5.0
    container_name: mealie
    restart: 'unless-stopped'
    ports:
        - "20000:9000"
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - /home/corum/docker/mealie:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "true"
      PUID: 1000
      PGID: 100
      TZ: Europe/Berlin
      BASE_URL: http://192.168.2.2
